version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - keda-db:/var/lib/postgresql/data

  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - keda-web:/var/lib/odoo
      - ./material_registration:/mnt/extra-addons/material_registration

volumes:
  keda-db:
  keda-web:
